// my-ecommerce-backend/models/transactionModel.js
const mongoose = require('mongoose');

const transactionSchema = new mongoose.Schema({
    // Link to the user who made the transaction
    user: {
        type: mongoose.Schema.ObjectId,
        ref: 'User', // References your User model
        required: true,
    },
    // Link to the order associated with this transaction
    order: {
        type: mongoose.Schema.ObjectId,
        ref: 'Order', 
        required: true,
    },
    // Payment Gateway specific details
    gateway: {
        type: String,
        required: true,
        enum: ['Paystack', 'Stripe', 'PayPal', 'Other'], // Add gateways you use
    },
    // Unique ID provided by the payment gateway for this specific transaction
    gatewayTransactionId: {
        type: String,
        required: true,
        unique: true, // This should be unique for each gateway transaction
    },
    // The reference generated by your system when initiating the transaction with the gateway
    // Paystack often uses this 'reference' as a key identifier.
    systemReference: {
        type: String,
        required: true,
        unique: true, // This should also be unique if you generate it per transaction attempt
    },
    amount: {
        type: Number,
        required: true,
        min: 0,
    },
    currency: {
        type: String,
        required: true,
        default: 'NGN', // Or 'USD', 'GHS', etc., based on your Paystack setup
    },
    // Status of the transaction (e.g., pending, successful, failed, reversed, refunded)
    status: {
        type: String,
        required: true,
        enum: ['pending', 'successful', 'failed', 'reversed', 'refunded'],
        default: 'pending',
    },
    // Optional: More details from the gateway's response (e.g., authorization code, card type)
    gatewayResponse: {
        type: Object, // Store the raw response object from the gateway if needed for debugging
        default: {},
    },
    // Optional: Reason for failure or refund
    reason: String,

    // Auto-generated timestamps for when the transaction was created and last updated
}, {
    timestamps: true,
});

module.exports = mongoose.model('Transaction', transactionSchema);